import type { Metadata } from 'next';
import { PrimeReactProvider } from 'primereact/api';

import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primeicons/primeicons.css';
import './globals.css';
import Image from 'next/image';


export const metadata: Metadata = {
  title: 'Quotation',
  description: 'Generated by Developer',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Using RootLayout");
  return (
    <html lang="en">
      <body className=" bg-[#fff] m-0 p-0 ">
        <PrimeReactProvider>
          <main className="h-screen bg-[#fff] overflow-auto no-scrollbar">{children}</main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
