import type { Metadata } from 'next';
import './globals.css';
import { PrimeReactProvider } from 'primereact/api';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Quotation',
  description: 'Generated by Developer',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-gray-100  overflow-hidden">
        <PrimeReactProvider>
          <header className="h-[90px] bg-[#222222] flex items-center">
            <div className="flex items-center gap-4">
              <Image src="/images/Logo.svg" alt="Logo" width={100} height={120} />
              <h1 className="text-white font-semibold text-lg">
                SHADOW TRADING W.L.L
              </h1>
            </div>
          </header>
          <main className="">{children}</main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
